### PR TITLE
Update current_year/start_year in demographics.py and defaults

### PR DESCRIPTION
**Pull request by rickecon**
This PR updates the `current_year` and `start_year` specifications in `demographics.py`. It also updates the `start_year` in `ogzaf_default_parameters.json` to be 2023. I am currently running this PR with PR #31 merged in and using that environment. I will report the results when it finishes.

cc: @jdebacker @SeaCelo

### CODE REVIEW

**Comment by rickecon** [comment]
@jdebacker and @SeaCelo I now this branch is up-to-date with the `main` branch. And the two example scripts run great. Below is the output. Now `OG-ZAF` works with start year 2023.

**`run_og_zaf.py` baseline steady-state equilibrium computation output**
```
GE loop errors =  [-1.3684192667895445e-13, -8.235079285157099e-14, -2.0032864256336325e-12, 0.0, 2.901456852555384e-12, -1.3537782006523003e-14, -2.4025920142278778e-14, 4.52589354882349e-14, 4.891920202254596e-14, 6.245004513516506e-16, -1.93345339738471e-13, -3.6228138544647237e-13, 1.160599394367523e-13, -9.171136072794184e-14]
Iteration: 01  Distance:  1.664968672730678e-11
SS debt =  1.5801364570181489 0.004347697805632564
IO:  (1, 1) , C:  (1,)
Foreign debt holdings =  0.37382143566088866
Foreign capital holdings =  1.9676355939324852
resource constraint:  [4.60742555e-15]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  1.2536638394067268e-12
Maximum error in savings FOC =  3.7125857943465235e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-Example/OUTPUT_BASELINE/SS/SS_vars.pklGE loop errors =  [-1.3684192667895445e-13, -8.235079285157099e-14, -2.0032864256336325e-12, 0.0, 2.901456852555384e-12, -1.3537782006523003e-14, -2.4025920142278778e-14, 4.52589354882349e-14, 4.891920202254596e-14, 6.245004513516506e-16, -1.93345339738471e-13, -3.6228138544647237e-13, 1.160599394367523e-13, -9.171136072794184e-14]
Iteration: 01  Distance:  1.664968672730678e-11
SS debt =  1.5801364570181489 0.004347697805632564
IO:  (1, 1) , C:  (1,)
Foreign debt holdings =  0.37382143566088866
Foreign capital holdings =  1.9676355939324852
resource constraint:  [4.60742555e-15]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  1.2536638394067268e-12
Maximum error in savings FOC =  3.7125857943465235e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-Example/OUTPUT_BASELINE/SS/SS_vars.pkl
```

**`run_og_zaf.py` baseline transition path equilibrium computation output (27 min, 18 sec)**
```
Maximum debt ratio:  1.2006758959428054
w diff:  1.7922294546224293e-06 1.1553817524934118e-07
r diff:  -6.7845709605940385e-09 -1.1482030922577158e-07
r_p diff:  -5.787914598986976e-09 -1.0061780615633342e-07
p_m diff:  0.0 0.0
BQ diff:  6.377739171781194e-07 -1.4122835129137812e-07
TR diff:  1.578408482735827e-07 -2.4435833005653773e-07
Iteration: 22
	Distance: 9.215459015202281e-06
Max absolute value resource constraint error: 2.032791816958257e-05
Checking time path for violations of constraints.
Max Euler error, savings:  8.250483629623773e-12
Max Euler error labor supply:  6.0609295360336546e-12
Time path iteration complete.
It took 1637.8391592502594 seconds to get that part done.
run time =  1637.839231967926
```

**`run_og_zaf.py` reform steady-state equilibrium computation output**
```
GE loop errors =  [1.3877787807814457e-17, 1.3877787807814457e-17, 6.661338147750939e-16, 0.0, 6.661338147750939e-16, 4.5102810375396984e-17, 5.898059818321144e-17, 5.204170427930421e-17, 3.8163916471489756e-16, 1.4085954624931674e-15, -1.1379786002407855e-15, -1.3704315460216776e-16, 2.7755575615628914e-17]
Iteration: 01  Distance:  2.4141267721327723e-14
SS debt =  1.5762085668577306 0.004336890334318699
IO:  (1, 1) , C:  (1,)
Foreign debt holdings =  0.372892193422116
Foreign capital holdings =  1.9409644173880864
resource constraint:  [-1.89848137e-14]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  1.2509993041476264e-12
Maximum error in savings FOC =  3.9612757518625585e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-Example/OUTPUT_REFORM/SS/SS_vars.pkl
```

**`run_og_zaf.py` reform transition path equilibrium computation output (25 min, 8 sec)**
```
Maximum debt ratio:  1.2003660595897703
w diff:  1.7602095205848656e-06 1.1422035517405504e-07
r diff:  -6.706673501277738e-09 -1.1283825116642499e-07
r_p diff:  -5.3327832080785065e-09 -9.842624425215885e-08
p_m diff:  0.0 0.0
BQ diff:  6.292469685170721e-07 -1.2936166482457878e-07
TR diff:  1.5538223281652552e-07 -2.4069714200936065e-07
Iteration: 22
	Distance: 7.78346473863651e-06
Max absolute value resource constraint error: 2.030419617871093e-05
Checking time path for violations of constraints.
Max Euler error, savings:  8.32911517534285e-12
Max Euler error labor supply:  6.10178574333986e-12
Time path iteration complete.
It took 1507.8616261482239 seconds to get that part done.
run time =  1507.861675977707
Percentage changes in aggregates: Year                    Variable  2023  2024  2025  ...  2031  2032  2023-2032    SS
0                    GDP ($Y_t$) -0.27 -0.26 -0.27  ... -0.26 -0.25      -0.26 -0.25
1            Consumption ($C_t$) -0.23  1.03 -0.21  ... -0.23 -0.23      -0.08 -0.26
2          Capital Stock ($K_t$) -0.62 -0.61 -0.63  ... -0.61 -0.60      -0.62 -0.62
3                  Labor ($L_t$)  0.01  0.02  0.01  ...  0.03  0.03       0.02  0.05
4     Real interest rate ($r_t$) -0.07 -0.07 -0.06  ... -0.07 -0.08      -0.07 -0.04
5                      Wage rate -0.28 -0.28 -0.29  ... -0.28 -0.28      -0.28 -0.29

[6 rows x 13 columns]
```

**`run_og_zaf_multiple_industry.py` baseline steady-state equilibrium computation output**
```
GE loop errors =  [8.625045122556685e-15, 9.943434964299058e-15, -4.143352327901084e-13, 5.484057652438423e-12, -1.4566126083082054e-13, -3.114175584073564e-13, 0.0, 2.0028423364237824e-13, -1.5543122344752192e-15, -1.8318679906315083e-15, -1.6930901125533637e-15, -1.0373646386341306e-15, -1.3183898417423734e-15, -2.248201624865942e-15, -3.7816971776294395e-16, 8.007483565108942e-15, 2.310651670001107e-15]
Iteration: 01  Distance:  2.8452127695511954e-12
SS debt =  3.3899923548701407 0.009327461724535604
IO:  (4, 5) , C:  (5,)
Foreign debt holdings =  0.8019888430195479
Foreign capital holdings =  10.784405815037521
resource constraint:  [ 4.02455846e-14  6.00908212e-15  2.34479103e-13 -3.73034936e-14]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  4.929390229335695e-13
Maximum error in savings FOC =  2.3447910280083306e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-CIT_Example/OUTPUT_BASELINE/SS/SS_vars.pkl
```

**`run_og_zaf_multiple_industry.py` baseline transition path equilibrium computation output (25 min, 12 sec)**
```
Maximum debt ratio:  2.4405998269210563
w diff:  6.7463897539532525e-06 1.2970390046440627e-06
r diff:  -3.3118089305672616e-08 -1.8799772365934997e-07
r_p diff:  -2.8727762051150574e-08 -1.66261337627982e-07
p_m diff:  0.0 -5.605512557238512e-06
BQ diff:  1.0101218769209552e-06 -1.5140770939781056e-07
TR diff:  -4.051417260009238e-08 -6.989998627970895e-07
Iteration: 21
	Distance: 9.895392646962732e-06
Max absolute value resource constraint error: 2.6126435435980255e-05
Checking time path for violations of constraints.
Max Euler error, savings:  2.877836857706484e-12
Max Euler error labor supply:  2.489564110419451e-12
Time path iteration complete.
It took 1511.8539009094238 seconds to get that part done.
run time =  1511.85396194458
```

**`run_og_zaf_multiple_industry.py` reform steady-state equilibrium computation output**
```
GE loop errors =  [-8.534839501805891e-16, -9.853229343548264e-16, 4.085620730620576e-14, 1.4654943925052066e-13, 3.2862601528904634e-14, 9.769962616701378e-15, 0.0, -3.241851231905457e-14, 2.463307335887066e-16, 4.371503159461554e-16, 5.759281940243e-16, 5.169475958410885e-16, 8.604228440844963e-16, 1.9012569296705806e-15, 3.122502256758253e-16, 0.0]
Iteration: 01  Distance:  7.60594088318558e-14
SS debt =  3.3942551270237797 0.009339190613554
IO:  (4, 5) , C:  (5,)
Foreign debt holdings =  0.802997310104331
Foreign capital holdings =  10.817493948723687
resource constraint:  [ 1.05471187e-15  1.42247325e-16  7.32747196e-15 -3.33066907e-14]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  4.982680934517703e-13
Maximum error in savings FOC =  2.362554596402333e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-CIT_Example/OUTPUT_REFORM/SS/SS_vars.pkl
```

**`run_og_zaf_multiple_industry.py` reform transition path equilibrium computation output (24 min, 21 sec)**
```
Maximum debt ratio:  2.445977453274021
w diff:  3.75668963892295e-06 8.576002064053512e-07
r diff:  -2.1854501812412774e-08 -1.0589004870859009e-07
r_p diff:  -1.896070632445568e-08 -9.257597766154646e-08
p_m diff:  0.0 -3.2086808934295163e-06
BQ diff:  6.3956317911118e-07 -7.658351769412874e-08
TR diff:  0.0 0.0
Iteration: 22
	Distance: 8.26381029898586e-06
Max absolute value resource constraint error: 2.6817769484210885e-05
Checking time path for violations of constraints.
Max Euler error, savings:  2.878808302853031e-12
Max Euler error labor supply:  2.4868995751603507e-12
Time path iteration complete.
It took 1461.3155250549316 seconds to get that part done.
run time =  1461.315574169159
Percentage changes in aggregates: Year                    Variable  2023  2024  2025  ...  2031  2032  2023-2032    SS
0                    GDP ($Y_t$) -0.02 -0.04  0.17  ...  0.14  0.14       0.12  0.13
1            Consumption ($C_t$)  0.02  0.29  0.16  ...  0.05  0.06       0.08  0.11
2          Capital Stock ($K_t$) -0.02 -0.04  0.29  ...  0.27  0.27       0.22  0.25
3                  Labor ($L_t$) -0.02 -0.03  0.03  ...  0.01  0.00       0.01 -0.01
4     Real interest rate ($r_t$) -0.00 -0.00  0.02  ...  0.02  0.02       0.01  0.01
5                      Wage rate  0.00  0.00  0.14  ...  0.14  0.14       0.11  0.14

[6 rows x 13 columns]
```

**Comment by jdebacker** [comment]
@rickecon @SeaCelo I've reviewed this PR and tested the example scripts with this change and it looks good to me.  Ready to merge!

**Comment by SeaCelo** [comment]
@rickecon I pulled this just now to test.  
- `run_og_zaf.py` fails during the baseline SS calculation, with `RuntimeError: Steady state aggregate resource constraint not satisfied`. 
- `run_og_zaf_multiple_industry.py` runs great (baseline and scenario)

**Comment by rickecon** [comment]
@SeaCelo. Did you update your environment from the last PR #31?

**Comment by SeaCelo** [comment]
Yes, and I confirmed it yesterday and again just now:
```
(ogzaf-dev) mlafleur@ProPro examples % conda list ogcore
# packages in environment at /Users/mlafleur/opt/anaconda3/envs/ogzaf-dev:
#
# Name                    Version                   Build  Channel
ogcore                    0.10.5                   pypi_0    pypi
```
I will do this again now to make sure I have the latest everything. Give me about 30 minutes.

**Comment by SeaCelo** [comment]
@rickecon Just removed the environment and re-created it (ensuring my repo was synched with EAPD). I got the same error in the single-sector script. What I did (form main branch):

```
% conda env remove -n ogzaf-dev
% conda env create -f environment.yml
% conda activate ogzaf-dev
% pip install -e .
% cd examples
% python run_og_zaf.py 
``` 

I'm sure I'm forgetting some step, so if it works on both of yours we should merge anyways and I'll track down the problem when I can sit with this for an hour or two.

**Comment by rickecon** [comment]
@SeaCelo and @jdebacker. I just re-ran the `run_og_zaf.py` and `run_og_zaf_multiple_industry.py` scripts in my `main` branch and in my `demog` branch (this would be `rickecon-demog` for you two). I ran the script until the baseline steady state solved and the transition path solved two iterations. In all four cases, the steady-state solved with no errors and the transition path was converging, as reported in my thread above.

**`run_og_zaf.py` output from `main` branch**
```
GE loop errors =  [3.95516952522712e-16, 4.163336342344337e-16, -5.329070518200751e-15, 0.0, -2.2604140781368187e-13, 1.2753686995381486e-13, 1.6085396903342541e-13, 1.1793344079080725e-13, 3.1356861551756765e-14, -5.936917624183025e-14, -4.05314670715029e-13, -3.707451012857632e-14, -9.041378756791119e-15, -1.942890293094024e-16]
Iteration: 01  Distance:  4.745598882969633e-12
SS debt =  1.5801213549646045 0.00434765625279061
IO:  (1, 1) , C:  (1,)
Foreign debt holdings =  0.3738178628863271
Foreign capital holdings =  1.9675258521401024
resource constraint:  [-6.28108676e-14]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  1.248778858098376e-12
Maximum error in savings FOC =  3.9612757518625585e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-Example/OUTPUT_BASELINE/SS/SS_vars.pkl
Government spending breakpoints are tG1:  20 ; and tG2: 256
Maximum debt ratio:  1.200875910678971
w diff:  0.08076689277091775 -0.005846681831134681
r diff:  0.0003425492185087295 -0.005194467327037343
r_p diff:  0.00028616947681227994 -0.0044883983413255835
p_m diff:  0.0 0.0
BQ diff:  0.006256115587980629 -0.0014826699056493808
TR diff:  0.0022161334991459905 -0.0003282478312936765
Iteration: 1
	Distance: 0.10977955089831681
Maximum debt ratio:  1.2006854185731148
w diff:  0.05247396270363747 -0.003069078380502299
r diff:  0.00017967615485021265 -0.0033499344119198166
r_p diff:  0.00015033366147505084 -0.0029088520533760917
p_m diff:  0.0 0.0
BQ diff:  0.004076900858645968 -0.0008540684458710895
TR diff:  0.0015506639314499387 -0.0002997960122821733
Iteration: 2
	Distance: 0.07438500537150003
```

**`run_og_zaf_multiple_industry.py` output from `main` branch**
```
GE loop errors =  [6.454559109414504e-14, 7.489842079877462e-14, -2.9198865547641617e-12, -7.311928840181281e-12, 1.4018564087336927e-11, -3.4130476223026562e-12, 0.0, 3.022471162239526e-12, -3.0867669531531305e-14, -3.2661373605691324e-14, -2.781108676686017e-14, -1.628211454551831e-14, -1.9713397581000436e-14, -3.4638958368304884e-14, -6.359496262930975e-15, 1.2090328738167955e-13, 1.026262408387879e-14]
Iteration: 01  Distance:  3.793873426101291e-12
SS debt =  3.3899678821064043 0.009327394388470498
IO:  (4, 5) , C:  (5,)
Foreign debt holdings =  0.8019830533653481
Foreign capital holdings =  10.784218027213374
resource constraint:  [-2.11969331e-13 -2.41716369e-14 -1.59661173e-12 -2.19824159e-13]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  4.9649173661237e-13
Maximum error in savings FOC =  2.504663143554353e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-CIT_Example/OUTPUT_BASELINE/SS/SS_vars.pkl
Government spending breakpoints are tG1:  20 ; and tG2: 256
Maximum debt ratio:  2.5787964723375825
w diff:  0.24585807795689796 0.028646148775320235
r diff:  -0.0007261632309062613 -0.0066732348854325815
r_p diff:  -0.0005965536548171307 -0.005789815907792956
p_m diff:  0.21431581645505782 0.0
BQ diff:  0.0074631920432516735 -0.0019258243677329895
TR diff:  0.005662637349715505 -0.0003794852105390295
Iteration: 1
	Distance: 0.13944620626174314
Maximum debt ratio:  2.5314814190193298
w diff:  0.09057668012921605 0.004140722590397328
r diff:  -0.00010783883180668502 -0.0026010038116603684
r_p diff:  -8.373185406602979e-05 -0.0022428892413963383
p_m diff:  0.0 -0.1297210739524921
BQ diff:  0.004895890921176663 -0.0005361914306085541
TR diff:  0.004664382282588392 -0.00025032470497055037
Iteration: 2
	Distance: 0.10958642789179256
```

**`run_og_zaf.py` output from `demog` branch**
```
GE loop errors =  [-1.3684192667895445e-13, -8.235079285157099e-14, -2.0032864256336325e-12, 0.0, 2.901456852555384e-12, -1.3537782006523003e-14, -2.4025920142278778e-14, 4.52589354882349e-14, 4.891920202254596e-14, 6.245004513516506e-16, -1.93345339738471e-13, -3.6228138544647237e-13, 1.160599394367523e-13, -9.171136072794184e-14]
Iteration: 01  Distance:  1.664968672730678e-11
SS debt =  1.5801364570181489 0.004347697805632564
IO:  (1, 1) , C:  (1,)
Foreign debt holdings =  0.37382143566088866
Foreign capital holdings =  1.9676355939324852
resource constraint:  [4.60742555e-15]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  1.2536638394067268e-12
Maximum error in savings FOC =  3.7125857943465235e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-Example/OUTPUT_BASELINE/SS/SS_vars.pkl
Government spending breakpoints are tG1:  20 ; and tG2: 256
Maximum debt ratio:  1.2008707341980691
w diff:  0.07940814923702422 -0.00573240432269162
r diff:  0.0003358809532163845 -0.005098054702196195
r_p diff:  0.00028018991742239513 -0.004408856771793937
p_m diff:  0.0 0.0
BQ diff:  0.006312478779957456 -0.001811297761336761
TR diff:  0.002160831997364207 -0.00017046553336725473
Iteration: 1
	Distance: 0.10799734629174935
Maximum debt ratio:  1.2006802140526636
w diff:  0.05161095043950148 -0.0029904199620580663
r diff:  0.00017508186734784686 -0.0032926380077833092
r_p diff:  0.00014635465828443522 -0.002858471146438453
p_m diff:  0.0 0.0
BQ diff:  0.00410508351864744 -0.0010840861471814872
TR diff:  0.001524608057922948 -0.0001689025416815801
Iteration: 2
	Distance: 0.07315302519103498
```

**`run_og_zaf_multiple_industry.py` output from `demog` branch**
```
GE loop errors =  [8.625045122556685e-15, 9.943434964299058e-15, -4.143352327901084e-13, 5.484057652438423e-12, -1.4566126083082054e-13, -3.114175584073564e-13, 0.0, 2.0028423364237824e-13, -1.5543122344752192e-15, -1.8318679906315083e-15, -1.6930901125533637e-15, -1.0373646386341306e-15, -1.3183898417423734e-15, -2.248201624865942e-15, -3.7816971776294395e-16, 8.007483565108942e-15, 2.310651670001107e-15]
Iteration: 01  Distance:  2.8452127695511954e-12
SS debt =  3.3899923548701407 0.009327461724535604
IO:  (4, 5) , C:  (5,)
Foreign debt holdings =  0.8019888430195479
Foreign capital holdings =  10.784405815037521
resource constraint:  [ 4.02455846e-14  6.00908212e-15  2.34479103e-13 -3.73034936e-14]
Checking constraints on capital, labor, and consumption.
	There were no violations of the constraints on labor  supply.
	There were no violations of the constraints on  consumption.
Maximum error in labor FOC =  4.929390229335695e-13
Maximum error in savings FOC =  2.3447910280083306e-13
JUST SAVED SS output to  /Users/richardevans/Docs/Economics/OSE/OG-ZAF/examples/OG-ZAF-CIT_Example/OUTPUT_BASELINE/SS/SS_vars.pkl
Government spending breakpoints are tG1:  20 ; and tG2: 256
Maximum debt ratio:  2.601167258068654
w diff:  0.24287509381487293 0.028931955823482625
r diff:  -0.0007334493691210364 -0.0065870222847283985
r_p diff:  -0.000599607373968962 -0.0057142593708746706
p_m diff:  0.21144576527041714 0.0
BQ diff:  0.007513091256886734 -0.0011397273023187326
TR diff:  0.005516743079302666 -0.0003149850479789579
Iteration: 1
	Distance: 0.13780000374225562
Maximum debt ratio:  2.5592605990456514
w diff:  0.08976218516596823 0.0034129461010796724
r diff:  -8.981498837747764e-05 -0.00256727221349122
r_p diff:  -6.797836815579383e-05 -0.0022138315203177675
p_m diff:  0.0 -0.12764360747607628
BQ diff:  0.004933340664689478 -0.0004576729187498463
TR diff:  0.004587678793160466 2.5077655497154905e-05
Iteration: 2
	Distance: 0.10785895067965401
```

**Comment by SeaCelo** [comment]
@rickecon Any chance we have some difference in our initial parameters? Looking at the last line of GE loop errors and the Iteration 01 results I see that our numbers are somewhat different:

**Comment by SeaCelo** [comment]
@rickecon 
Screenshot 2023-02-15 at 12 51 07 PM

**Comment by rickecon** [comment]
@SeaCelo. Try this command. Go to your `main` branch in your terminal and type the following:
```
git diff --name-status  upstream/main
```

That should tell you if any files in your `main` repository on your fork on your local machine are different from the files in the remote main `EAPD-DRB/OG-ZAF` repository.

**Comment by SeaCelo** [comment]
Merging, and I'll try to solve my issues later

**Comment by SeaCelo** [comment]
@rickecon I tried the command from my OG-ZAF directory (and in my `main` branch locally):

`git diff --name-status  upstream/main`
No results. I'm identical to upstream but I still get the error. I'll spend more time tracking this down over the weekend.

**Pull request merged**
