### PR TITLE
Update get_e_orig() with an adjustment by age calibration for ZAF

### LINKED ISSUE #18: Compute lifetime earnings profiles
Preparing the lifetime earnings profiles for ZAF using data from the [Luxembourg Income Study (LIS)](https://www.lisdatacenter.org), available in their [LISSY portal](http://www.lisdatacenter.org/data-access/lissy/syntax/). 

For South Africa, the LIS has a survey from 2017 which includes total wages as well as hours worked for each individual. Their description of the data is available in their [METIS site](http://www.lisdatacenter.org/frontend#/database/1/selection).

The strategy is to use wages/hour as a measure of productivity, and reporting it by age (s) and by income group (j). 

The computation generally follows the procedure described in the [OG-USA calibration of lifetime earnings profiles](https://pslmodels.github.io/OG-USA/content/calibration/earnings.html).

1. Download wage/hour in SxJ dimensions
2. Normalize them by the mean of each J income group
3. Take natural log
4. Fill in missing values by regressing ln(productivity) on age, age^2 by each J income group

This is all done with Stata code in the LISSY interface, and manually formatted into a simple CSV with SxJ dimensions.

I'm attaching the results: 
[productivity_modelled.csv](https://github.com/EAPD-DRB/OG-ZAF/files/10045199/productivity_modelled.csv)

The .do file is attached (as a zip). [lissy2.do.zip](https://github.com/EAPD-DRB/OG-ZAF/files/10045183/lissy2.do.zip)

@rickecon Let me know if you think this calculation is reasonable. In the US calibration you do more to compute present value and your range looks different, so we would probably have to adjust this further.

### PR DESCRIPTION
**Pull request by marcelolafleur**
This PR applies the first of 2 calibration adjustments to the lifetime earning profile curve of the USA using ZAF data. 

The adjustments are needed because the lifetime earning profile curve are only computed using USA data. For most other countries, including ZAF, the data needed to compute country-specific curves is not available from public sources or surveys.

We start from the proposition that the estimated USA curves represent a generalized relationship between age and lifetime income. We then adjust this generalized shape in two ways:
1. "adjustment by age": adjust the shape of all the USA curves to match the target country's national distribution of income per capita for each age year
2. "adjustment by income": adjust the gaps between the USA curves to match the target country's distribution between the J-income groups

Steps:
1. Using data from NTA project, we compare the differences in income per capita between the USA and ZAF at each age. 
2. The ability paths of the USA are adjusted by this difference at each age.
3. Fit a cubic regression on the adjusted data.
4. Estimated the adjusted ability paths using the estimated coefficients. 

The PR uses only the hardcoded estimated coefficients. The full estimation is not included and will be left to a future PR with a new function that can be used for any country. 

*NTA data is available from: https://ntaccounts.org/web/nta/show/Browse%20database
We use "Smooth Mean: Per capita, smoothed values."

### CODE REVIEW

**Comment by SeaCelo** [comment]
I am updating this PR with the additional adjustment based on income inequality. This PR now has two adjustments in this order:

1. Adjustment by income (J): adjust the gaps between the J-income earning curves using data from WID.
2. Adjustment by age (S): adjust the shape/distribution of each J-income earning profile curve using data from NTA.

I opted to use the (J) adjustment first because otherwise the adjusted lines would cross at older ages. This order gives cleaner results, at least for ZAF.

To make the adjustment I compute 2 adjustment factors: 
1) `factor_j` is the ratio of the income shares for each of the 7 levels of `J`. Dimension is (1,7). Source is WID.
2) `factor_s` is the ratio of the income per capita of each age group `S`. Dimension is (60,1). Source is NTA.

The adjustment algorithm is:

1. Compute the original ability paths
2. Multiply by `factor_j`
3. Multiply by `factor_s`
4. Re-estimate the cubic equation. The coefficients are included in the changes to `income.py`
5. Compute and scale the new ability paths.

Compare the results

USA (scaled)
image

ZAF (adjusted by J+S and scaled)
image


Jupyter notebook is included with all the steps replicated.
[LIC_byJ-byS.ipynb.zip](https://github.com/EAPD-DRB/OG-ZAF/files/10439806/LIC_byJ-byS.ipynb.zip)

cc: @rickecon and @sarvonz

**Comment by SeaCelo** [comment]
```
#Compare the shares of income from the WID database
#source: https://wid.world/data/
#sptinc_992_j for USA and for ZAF
#Pre-tax national income share | adults | equal split
#p0p25, p25p50, p50p70, p70p80, p80p90, p90p99, p99p100
#factor_j = ZAF/USA shares

factor_j = np.array(
    [
        0.378548895899054, 
        0.432562620423893, 
        0.506756756756757, 
        0.666977611940298, 
        0.939575033200531, 
        1.73503951825367, 
        1.01471361008933, 
    ]
)

```

```
factor_s = np.array(
    [0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.23990469, 0.24220296, 0.30220568, 0.35593232,
       0.4257811 , 0.58896071, 0.69224204, 0.78225281, 0.83936604,
       0.89005477, 0.89659914, 0.90808553, 0.89889603, 0.93106417,
       1.01425339, 1.11462065, 1.14872412, 1.21100919, 1.25553409,
       1.24542311, 1.20886907, 1.19818604, 1.16236542, 1.13575846,
       1.1469575 , 1.16880459, 1.13490948, 1.13696164, 1.13925097,
       1.10452374, 1.09281686, 1.12765468, 1.14409922, 1.12994496,
       1.11015196, 1.14480588, 1.13137263, 1.11145134, 1.13512537,
       1.12952015, 1.14793555, 1.09555823, 0.98800162, 0.99444266,
       0.93571283, 0.88492352, 0.81181711, 0.76183153, 0.63231938,
       0.58240847, 0.51668169, 0.46816986, 0.42942588, 0.35685632,
       0.33608736, 0.20413355, 0.1680406 , 0.14894733, 0.15135708,
       0.12241949, 0.12556212, 0.13603321, 0.13577661, 0.10153023,
       0.10588211, 0.10228357, 0.10159435, 0.122539  , 0.11061828,
       0.04071573, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ]
)
```

**Comment by SeaCelo** [comment]
The model solves with the following solution. From my perspective it is ready to be merged pending any further calibration and additional tests. 
@rickecon @sarvonz 

```
Percentage changes in aggregates: Year                    Variable  2021  2022  2023  2024  2025  2026  2027  2028  2029  2030  2021-2030    SS
0                    GDP ($Y_t$) -0.19 -0.19 -0.20 -0.20 -0.20 -0.20 -0.18 -0.17 -0.17 -0.16      -0.19 -0.37
1            Consumption ($C_t$) -0.22  0.89  0.30 -0.08 -0.15 -0.20 -0.21 -0.23 -0.23 -0.23      -0.00 -0.08
2          Capital Stock ($K_t$) -0.41 -0.41 -0.43 -0.44 -0.44 -0.44 -0.42 -0.41 -0.40 -0.40      -0.42 -0.76
3                  Labor ($L_t$) -0.01 -0.01 -0.01 -0.01 -0.01 -0.01  0.01  0.02  0.02  0.02       0.00 -0.06
4     Real interest rate ($r_t$) -0.06 -0.06 -0.04 -0.03 -0.03 -0.03 -0.03 -0.04 -0.04 -0.04      -0.04  0.31
5                      Wage rate -0.18 -0.18 -0.19 -0.19 -0.19 -0.19 -0.19 -0.19 -0.19 -0.19      -0.19 -0.31

```

**Comment by rickecon** [comment]
@SeaCelo. This PR looks great. I made [a PR](https://github.com/SeaCelo/OG-ZAF/pull/2) to your branch with some documentation, calibration, and run script updates. As soon as you review that and merge that into your branch, I will be ready to merge this PR.

**Comment by SeaCelo** [comment]
I merged your PR and this should be ready to merge into main. @rickecon @sarvonz

**Comment by rickecon** [comment]
Looks great. Thanks @SeaCelo. Merging.

**Pull request merged**
