### PR TITLE
Calibrate IO matrix

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds a script, `input_output.py`, which calibrates the `alpha_c` vector and the `io_matrix` array using the South Africa Social Accounting Matrix (SAM) [file provided by the United Nations University - Wider](https://www.wider.unu.edu/database/2015-social-accounting-matrix-south-africa).

The dimensions of this calibration (4 production industries, 5 consumption categories) and their mappings to the micro SAM consumption and production categories is set in `constants.py`.  At some point, we can make these flexible simply by adding arguments to pass the consumption and production dictionaries (similar to what is now in `constants.py`) to the initialization of a `Calibration` class object or by including these are parameters in the `ogcore.Specifications` object.  But for now, this PR is helpful in allowing one to toggle between a simple single sector/single good model and a 5 good, 4 production sector model.

I also add another example script which shows how one might configure a run with multiple goods and industries based off of the calibration described above.

### CODE REVIEW

**Comment by SeaCelo** [comment]
`RuntimeError: Steady state equilibrium not found` @jdebacker

**Comment by jdebacker** [comment]
@SeaCelo Thanks for testing this!

Can you tell me - was the SS failure on the reform run?  I had it break there because the proposed reform didn't conform with the latest baseline parameterization (I hadn't updated that). 

My latest commit changes the reform to consider a CIT rate cut from a statutory rate of 28% to 27% in 2023.  I'm running it now, but this should not break.

**Comment by SeaCelo** [comment]
It was in the reform scenario. I'll test the new scenario as well

**Comment by SeaCelo** [comment]
@jdebacker I tried it again with your new reform scenario and it also didn't find an equilibrium in the reform scenario.

**Comment by jdebacker** [comment]
@SeaCelo I found the issue.  The reform wasn't using the baseline solutions as starting values due to an issue comparing array dimensions to a scalar in `ogcore.SS` (e.g., it was saying that `(4,)` did not equal `4` and therefore tossed out the baseline solution as starting values).  I'm fixing that in OG-Core in [PR #854](https://github.com/PSLmodels/OG-Core/pull/854).  In the meantime, I'm running this reform on my machine now.

**Comment by SeaCelo** [comment]
Good catch. Let us know when OG-Core is updated and I'll re-install it

**Comment by SeaCelo** [comment]
@jdebacker @rickecon I'm running the example now but I had to solve an unrelated error: I removed and re-created my environment to install the newest version of OG-Core (with PR #854). When I tried to run Jason's example script, I got this [openpyxl error](https://stackoverflow.com/questions/75440354/why-does-pandas-read-excel-fail-on-an-openpyxl-error-saying-readonlyworksheet).

The solution is simply to downgrade openpyxl from 10.1.1 to 10.1.0. If this is confirmed this needs to be pinned during the environment installation.

**Comment by jdebacker** [comment]
Adding pin to `openpyxl` to resolve Issue #32

**Review by rickecon — APPROVED** [review]

**Comment by jdebacker** [comment]
I did have missing piece that I think I got with the last commit (for the case of a single industry and good).  But this is now ready for review.  And you might do so by running both example scripts (the single and multiple industries versions) to make sure they work for you.

cc @SeaCelo @rickecon

**Comment by rickecon** [comment]
@jdebacker @SeaCelo. I have reviewed and approved all the code. That `input_output.py` module is so good! I am just running the two example scripts on my machine right now. As soon as those two run successfully, I will merge this.

**Comment by SeaCelo** [comment]
Running them now. The `input_output.py` code is very elegant...

**Comment by SeaCelo** [comment]
Good solutions for me

**Comment by rickecon** [comment]
@SeaCelo. You ran both example scripts, baseline steady state and transition path, and reform steady-state and transition path? If so, go ahead and merge this. You do the honors.

**Comment by SeaCelo** [comment]
@rickecon just the multi sector for now. I have to run home and will run the single sector there. But if it works for you go ahead

**Comment by rickecon** [comment]
@jdebacker and @SeaCelo. Two weird things going on right now with this PR.
1. The "Check that docs build" GitHub Action test is taking forever, then erroring out. We'll see if it passes this time.
2. My run of `run_og_zaf.py` is cycling in the reform TPI around a distance of 2.0-e05. We'll see if that ends up solving. It would be great if someone could confirm this.

**Comment by rickecon** [comment]
My run of `run_og_zaf.py` finished. Merging.

**Comment by rickecon** [comment]
Merging.

**Comment by SeaCelo** [comment]
My run of `run_og_zaf.py` finished as well.

**Pull request merged**
