### PR TITLE
Update demographics.py

### PR DESCRIPTION
**Pull request by sarvonz**
Retrieve neonatal mortality rate data from WB WDI.

### CODE REVIEW

**Comment by rickecon** [comment]
@sarvonz. Will you please make this PR to @rickecon's branch for PR #14. Once you submit that PR, I will close this PR. Follow these instructions.
* Go to your terminal, navigate to the `main` branch of your `OG-ZAF` repository, and create a branch copy of Rick's branch by typing the following two commands in succession.
```
git checkout -b rickecon-demog main
git pull https://github.com/rickecon/OG-ZAF.git demog
```
* Make your changes to the `demographics.py` file in your `rickecon-demog` branch, and commit those changes and push those  changes up to a new branch on your remote `origin` repository. (You might need to do the push command from GitHub Desktop).
* Submit a pull request from your `rickecon-demog` branch to `rickecon/OG-ZAF/` `demog` branch. This is done online from your GitHub repository on the web.

Let me know if you have any questions.

**Review by SeaCelo — CHANGES_REQUESTED** [review]
The code looks fine. A future request would be to check that the returned data is not missing since we can give it a data range.

Please follow the instructions to create a PR into Rick's code:  https://github.com/EAPD-DRB/OG-ZAF/pull/19#issuecomment-1325582701  

That PR will get merged. This one would be deleted.

**Comment by sarvonz** [comment]
@SeaCelo thank you. I already submitted the PR to @rickecon demog branch per his instructions. If Rick can confirm that the submission was done properly, I can delete this PR.

**Comment by SeaCelo** [comment]
> @SeaCelo thank you. I already submitted the PR to @rickecon demog branch per his instructions. If Rick can confirm that the submission was done properly, I can delete this PR.

@rickecon Please confirm that the PR was submitted so we can close this one.

**Comment by rickecon** [comment]
@sarvonz @SeaCelo. This PR was made to @rickecon's branch in PR #14. However, I decided to make a new function `get_wb_infmort_rate()` in `demographics.py` and to put the call to the infant mortality rate in the `get_mort()` function. So we can close this PR.

**Pull request closed without merging**
