### PR TITLE
Updated the sweetness of households

### PR DESCRIPTION
**Pull request by rickecon**
This PR updates mortality rates and the Frisch elasticity of labor supply, consistent with South Africans eating more candy. @jdebacker @SeaCelo

### CODE REVIEW

**Comment by jdebacker** [comment]
@rickecon Where are you getting these parameter values?  Can you cite some research?

**Comment by SeaCelo** [comment]
@rickecon I like candy too, but this probably shouldn't be merged....Do we have literature to support this?

**Comment by rickecon** [comment]
@jdebacker . It's just a feeling!

**Comment by jdebacker** [comment]
@rickecon Why don't you find some documentation before we consider merging.

**Pull request closed without merging**
